baseURL = 'https://ocf.berkeley.edu/~matienzo'
languageCode = 'en-us'
pluralizeListTitles = false
title = 'mar√≠a a. matienzo'

[module]
    [[module.imports]]
        path = 'github.com/anarchivist/hugo-tufte'

[params]
    orcid = '0000-0003-3270-1306'
    google_scholar = 'UCaROGcAAAAJ'
    github = 'anarchivist'
    subtitle = 'Head of Application Development Services, UC Berkeley Library'

[menus]
    [[menus.nav]]
        name = 'Home'
        pageRef = '/'
        weight = 10
    [[menus.nav]]
        name = 'Worklog'
        pageRef = '/worklog'
        weight = 20

[permalinks]
    [permalinks.page]
        worklog = '/:year/:002/:slug/'

[markup]
    [markup.goldmark.renderer]
        unsafe = true